### ISSUE TITLE
state tipoDeUsuario não é alterada

### ISSUE THREAD

**Issue by JonathanAllisson** [davidedup/reclame-aqui-ufcg#4]
No componente de reclamacaoCreator, no formulario existe um select option onde esse select tem o valor do state tipoDeUsuario, mas esse state não é alterado após escolher umas das options pois as options não possuem a atributo "value" como pode ser visto no exemplo desse site: https://www.w3schools.com/tags/tag_option.asp
Talvez você só não tenha lembrado de ter colocado esse atributo nas options, mas o projeto tá bem legal e caso não conheça esse site, ele tem varias dicas massas, vlw

**Comment by davidedup** [comment]
Done
